/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited.
// Auto-generated by Next.js — regenerated when `next dev` or `next build` runs.
