import type { FoodItem } from '@thali/types';

/**
 * Normalized static food dataset for Thali Tracker.
 * Spans Bengali home dishes, Western staples, generic staples, and packaged goods.
 *
 * All cuisine tags are purely metadata for search relevance / ranking,
 * never database dividers or exclusionary filters.
 */
export const FOOD_DATASET: FoodItem[] = [
  // =========================================================================
  // 1. BENGALI HOME DISHES (15 items)
  // =========================================================================
  {
    id: 'food_bengali_sada_bhat',
    canonicalName: 'Steamed White Rice',
    localNames: ['ভাত', 'সাদা ভাত', 'Sada Bhat', 'Bhat'],
    aliases: ['Plain Rice', 'Boiled Rice', 'Cooked White Rice'],
    cuisineTags: ['bengali', 'south_asian', 'staple'],
    category: 'grain',
    caloriesPer100g: 130,
    proteinPer100g: 2.7,
    carbsPer100g: 28.2,
    fatPer100g: 0.3,
    fiberPer100g: 0.4,
    commonServings: [
      { label: '1 medium cup (cooked)', grams: 150 },
      { label: '1 plate / thali portion', grams: 250 },
      { label: '1 small bowl', grams: 100 },
    ],
    source: 'Bangladesh Food Composition Table (FCTB)',
    sourceVersion: '2013-v1',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_bengali_moshur_dal',
    canonicalName: 'Bengali Red Lentil Dal',
    localNames: ['মসুর ডাল', 'Moshur Dal', 'Macher Jholer Shonge Dal'],
    aliases: ['Red Lentil Soup', 'Masoor Dal', 'Pabla Dal'],
    cuisineTags: ['bengali', 'south_asian'],
    category: 'pulse',
    caloriesPer100g: 85,
    proteinPer100g: 5.5,
    carbsPer100g: 12.0,
    fatPer100g: 1.8,
    fiberPer100g: 2.1,
    commonServings: [
      { label: '1 medium bowl / bati', grams: 150 },
      { label: '1 large bowl', grams: 250 },
      { label: '1 ladle / chamoch', grams: 60 },
    ],
    source: 'Bangladesh Food Composition Table (FCTB)',
    sourceVersion: '2013-v1',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_bengali_rui_macher_jhol',
    canonicalName: 'Rohu Fish Curry',
    localNames: ['রুই মাছের ঝোল', 'Rui Macher Jhol', 'Rui Macher Kalia'],
    aliases: ['Rohu Curry', 'Carp Fish Curry', 'Bengali Fish Stew'],
    cuisineTags: ['bengali', 'south_asian'],
    category: 'protein',
    caloriesPer100g: 125,
    proteinPer100g: 14.5,
    carbsPer100g: 3.2,
    fatPer100g: 6.0,
    fiberPer100g: 0.8,
    commonServings: [
      { label: '1 piece with gravy (peti/gada)', grams: 120 },
      { label: '2 pieces with gravy', grams: 240 },
    ],
    source: 'Bangladesh Food Composition Table (FCTB)',
    sourceVersion: '2013-v1',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_bengali_ilish_macher_jhol',
    canonicalName: 'Hilsa Fish Curry',
    localNames: ['ইলিশ মাছের ঝোল', 'Ilish Macher Jhol', 'Shorshe Ilish'],
    aliases: ['Hilsa Curry', 'Mustard Hilsa', 'Ilish Jhol'],
    cuisineTags: ['bengali', 'south_asian'],
    category: 'protein',
    caloriesPer100g: 220,
    proteinPer100g: 16.0,
    carbsPer100g: 2.5,
    fatPer100g: 16.2,
    fiberPer100g: 0.5,
    commonServings: [
      { label: '1 piece with gravy', grams: 125 },
      { label: '1 large steak portion', grams: 175 },
    ],
    source: 'Bangladesh Food Composition Table (FCTB)',
    sourceVersion: '2013-v1',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_bengali_murgir_jhol',
    canonicalName: 'Bengali Chicken Curry',
    localNames: ['মুরগির ঝোল', 'Murgir Jhol', 'Murgir Mangsho'],
    aliases: ['Chicken Jhol', 'Bengali Chicken with Potato', 'Desi Chicken Curry'],
    cuisineTags: ['bengali', 'south_asian'],
    category: 'protein',
    caloriesPer100g: 145,
    proteinPer100g: 15.2,
    carbsPer100g: 4.8,
    fatPer100g: 7.3,
    fiberPer100g: 0.9,
    commonServings: [
      { label: '2 small pieces with potato & gravy', grams: 180 },
      { label: '3 pieces medium serving', grams: 260 },
    ],
    source: 'Bangladesh Food Composition Table (FCTB)',
    sourceVersion: '2013-v1',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_bengali_dimer_dalna',
    canonicalName: 'Bengali Egg Curry',
    localNames: ['ডিমের ডালনা', 'Dimer Dalna', 'Dimer Kalia'],
    aliases: ['Egg Potato Curry', 'Dimer Jhol'],
    cuisineTags: ['bengali', 'south_asian'],
    category: 'protein',
    caloriesPer100g: 135,
    proteinPer100g: 8.5,
    carbsPer100g: 6.2,
    fatPer100g: 8.4,
    fiberPer100g: 1.1,
    commonServings: [
      { label: '1 egg with gravy & potato piece', grams: 130 },
      { label: '2 eggs with gravy', grams: 220 },
    ],
    source: 'Bangladesh Food Composition Table (FCTB)',
    sourceVersion: '2013-v1',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_bengali_shobji_bhaji',
    canonicalName: 'Mixed Vegetable Stir-Fry',
    localNames: ['সবজি ভাজি', 'Shobji Bhaji', 'Pechimeshi Shobji'],
    aliases: ['Bengali Mixed Veg', 'Pape Shobji Bhaji', 'Vegetable Fry'],
    cuisineTags: ['bengali', 'south_asian'],
    category: 'vegetable',
    caloriesPer100g: 72,
    proteinPer100g: 2.1,
    carbsPer100g: 8.4,
    fatPer100g: 3.5,
    fiberPer100g: 2.8,
    commonServings: [
      { label: '1 small bowl', grams: 100 },
      { label: '1 standard cup serving', grams: 150 },
    ],
    source: 'Bangladesh Food Composition Table (FCTB)',
    sourceVersion: '2013-v1',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_bengali_alu_bharta',
    canonicalName: 'Bengali Mashed Potato',
    localNames: ['আলু ভর্তা', 'Alu Bharta', 'Aloo Bhate'],
    aliases: ['Mashed Potato with Mustard Oil', 'Aloo Chokha', 'Spicy Potato Mash'],
    cuisineTags: ['bengali', 'south_asian'],
    category: 'vegetable',
    caloriesPer100g: 110,
    proteinPer100g: 2.0,
    carbsPer100g: 17.5,
    fatPer100g: 3.8,
    fiberPer100g: 1.8,
    commonServings: [
      { label: '1 round bharta ball / gola', grams: 50 },
      { label: '2 bharta balls', grams: 100 },
    ],
    source: 'Bangladesh Food Composition Table (FCTB)',
    sourceVersion: '2013-v1',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_bengali_begun_bhaja',
    canonicalName: 'Fried Eggplant / Begun Bhaja',
    localNames: ['বেগুন ভাজা', 'Begun Bhaja'],
    aliases: ['Eggplant Fry', 'Aubergine Fry', 'Baingan Fry'],
    cuisineTags: ['bengali', 'south_asian'],
    category: 'vegetable',
    caloriesPer100g: 140,
    proteinPer100g: 1.6,
    carbsPer100g: 9.2,
    fatPer100g: 11.0,
    fiberPer100g: 3.4,
    commonServings: [
      { label: '1 round slice', grams: 60 },
      { label: '2 slices', grams: 120 },
    ],
    source: 'Bangladesh Food Composition Table (FCTB)',
    sourceVersion: '2013-v1',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_bengali_shaak_bhaji',
    canonicalName: 'Stir-Fried Leafy Greens',
    localNames: ['শাক ভাজি', 'Shaak Bhaji', 'Palong Shaak', 'Lal Shaak'],
    aliases: ['Spinach Fry', 'Red Amaranth Fry', 'Saag Bhaji'],
    cuisineTags: ['bengali', 'south_asian'],
    category: 'vegetable',
    caloriesPer100g: 58,
    proteinPer100g: 2.9,
    carbsPer100g: 4.5,
    fatPer100g: 3.2,
    fiberPer100g: 2.6,
    commonServings: [
      { label: '1 small katori / bowl', grams: 80 },
      { label: '1 standard serving', grams: 120 },
    ],
    source: 'Bangladesh Food Composition Table (FCTB)',
    sourceVersion: '2013-v1',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_bengali_chholar_dal',
    canonicalName: 'Chana Dal / Bengal Gram Dal',
    localNames: ['ছোলার ডাল', 'Chholar Dal', 'Chana Dal with Coconut'],
    aliases: ['Bengal Gram Dal', 'Sweet and Savory Chholar Dal'],
    cuisineTags: ['bengali', 'south_asian'],
    category: 'pulse',
    caloriesPer100g: 140,
    proteinPer100g: 6.8,
    carbsPer100g: 19.5,
    fatPer100g: 4.2,
    fiberPer100g: 4.5,
    commonServings: [
      { label: '1 medium bowl', grams: 150 },
      { label: '1 large bowl', grams: 220 },
    ],
    source: 'Bangladesh Food Composition Table (FCTB)',
    sourceVersion: '2013-v1',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_bengali_khasir_mangsho',
    canonicalName: 'Bengali Mutton / Goat Curry',
    localNames: ['খাসির মাংস', 'Khasir Mangsho', 'Kosha Mangsho'],
    aliases: ['Goat Meat Curry', 'Mutton Kosha', 'Bengali Lamb Curry'],
    cuisineTags: ['bengali', 'south_asian'],
    category: 'protein',
    caloriesPer100g: 215,
    proteinPer100g: 17.5,
    carbsPer100g: 4.1,
    fatPer100g: 14.2,
    fiberPer100g: 0.6,
    commonServings: [
      { label: '2 pieces with gravy', grams: 160 },
      { label: '3 pieces hearty serving', grams: 240 },
    ],
    source: 'Bangladesh Food Composition Table (FCTB)',
    sourceVersion: '2013-v1',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_bengali_khichuri',
    canonicalName: 'Bengali Khichuri / Rice & Lentil Porridge',
    localNames: ['খিচুড়ি', 'Khichuri', 'Bhuna Khichuri', 'Patla Khichuri'],
    aliases: ['Khichdi', 'Yellow Lentil Rice Stew'],
    cuisineTags: ['bengali', 'south_asian', 'staple'],
    category: 'grain',
    caloriesPer100g: 148,
    proteinPer100g: 4.8,
    carbsPer100g: 24.2,
    fatPer100g: 3.6,
    fiberPer100g: 2.2,
    commonServings: [
      { label: '1 plate', grams: 250 },
      { label: '1 bowl', grams: 180 },
    ],
    source: 'Bangladesh Food Composition Table (FCTB)',
    sourceVersion: '2013-v1',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_bengali_ruti',
    canonicalName: 'Handmade Whole Wheat Roti',
    localNames: ['রুটি', 'আটার রুটি', 'Atta Ruti', 'Roti', 'Chapati'],
    aliases: ['Tawa Roti', 'Whole Wheat Flatbread', 'Chapatti'],
    cuisineTags: ['bengali', 'south_asian', 'staple'],
    category: 'grain',
    caloriesPer100g: 264,
    proteinPer100g: 9.1,
    carbsPer100g: 53.5,
    fatPer100g: 1.4,
    fiberPer100g: 6.8,
    commonServings: [
      { label: '1 medium roti', grams: 40 },
      { label: '2 medium rotis', grams: 80 },
      { label: '3 medium rotis', grams: 120 },
    ],
    source: 'Bangladesh Food Composition Table (FCTB)',
    sourceVersion: '2013-v1',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_bengali_mishti_doi',
    canonicalName: 'Bengali Sweet Curd / Mishti Doi',
    localNames: ['মিষ্টি দই', 'Mishti Doi', 'Misti Doi'],
    aliases: ['Sweet Yogurt', 'Caramelized Yogurt'],
    cuisineTags: ['bengali', 'south_asian', 'dessert'],
    category: 'dairy',
    caloriesPer100g: 155,
    proteinPer100g: 4.2,
    carbsPer100g: 23.0,
    fatPer100g: 5.2,
    fiberPer100g: 0.0,
    commonServings: [
      { label: '1 small clay pot / matka cup', grams: 100 },
      { label: '1 large serving', grams: 180 },
    ],
    source: 'Bangladesh Food Composition Table (FCTB)',
    sourceVersion: '2013-v1',
    verifiedAt: '2026-01-15',
  },

  // =========================================================================
  // 2. WESTERN BASICS (12 items)
  // =========================================================================
  {
    id: 'food_western_grilled_chicken_breast',
    canonicalName: 'Grilled Chicken Breast',
    localNames: ['গ্রিলড চিকেন ব্রেস্ট'],
    aliases: ['Chicken Breast Skinless Cooked', 'Boneless Grilled Chicken'],
    cuisineTags: ['western', 'lean_protein'],
    category: 'protein',
    caloriesPer100g: 165,
    proteinPer100g: 31.0,
    carbsPer100g: 0.0,
    fatPer100g: 3.6,
    fiberPer100g: 0.0,
    commonServings: [
      { label: '1 breast fillet', grams: 150 },
      { label: '1/2 breast fillet', grams: 75 },
    ],
    source: 'USDA FoodData Central',
    sourceVersion: 'SR Legacy 2019',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_western_boiled_egg',
    canonicalName: 'Hard-Boiled Whole Egg',
    localNames: ['সিদ্ধ ডিম', 'Sheddho Dim'],
    aliases: ['Boiled Egg', 'Large Boiled Egg'],
    cuisineTags: ['western', 'generic', 'staple'],
    category: 'protein',
    caloriesPer100g: 155,
    proteinPer100g: 12.6,
    carbsPer100g: 1.1,
    fatPer100g: 10.6,
    fiberPer100g: 0.0,
    commonServings: [
      { label: '1 large egg', grams: 50 },
      { label: '2 large eggs', grams: 100 },
    ],
    source: 'USDA FoodData Central',
    sourceVersion: 'SR Legacy 2019',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_western_rolled_oats',
    canonicalName: 'Rolled Oats (Dry)',
    localNames: ['ওটস', 'Oats'],
    aliases: ['Old Fashioned Oats', 'Oatmeal Dry', 'Porridge Oats'],
    cuisineTags: ['western', 'generic', 'staple'],
    category: 'grain',
    caloriesPer100g: 389,
    proteinPer100g: 16.9,
    carbsPer100g: 66.3,
    fatPer100g: 6.9,
    fiberPer100g: 10.6,
    commonServings: [
      { label: '1/2 cup dry oats', grams: 40 },
      { label: '1 cup dry oats', grams: 80 },
    ],
    source: 'USDA FoodData Central',
    sourceVersion: 'SR Legacy 2019',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_western_whole_milk',
    canonicalName: 'Pasteurized Whole Cow Milk',
    localNames: ['গরুর দুধ', 'Dudh', 'Full Cream Milk'],
    aliases: ['Whole Milk', 'Standardized Cow Milk 3.5% Fat'],
    cuisineTags: ['western', 'generic', 'dairy'],
    category: 'dairy',
    caloriesPer100g: 61,
    proteinPer100g: 3.2,
    carbsPer100g: 4.8,
    fatPer100g: 3.3,
    fiberPer100g: 0.0,
    commonServings: [
      { label: '1 glass / mug', grams: 240 },
      { label: '1 small cup (tea/coffee addition)', grams: 100 },
    ],
    source: 'USDA FoodData Central',
    sourceVersion: 'SR Legacy 2019',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_western_greek_yogurt_plain',
    canonicalName: 'Plain Greek Yogurt (0% Fat)',
    localNames: ['গ্রিক দই', 'Greek Yogurt'],
    aliases: ['Nonfat Greek Yogurt', 'Strained Yogurt'],
    cuisineTags: ['western', 'dairy', 'high_protein'],
    category: 'dairy',
    caloriesPer100g: 59,
    proteinPer100g: 10.2,
    carbsPer100g: 3.6,
    fatPer100g: 0.4,
    fiberPer100g: 0.0,
    commonServings: [
      { label: '1 cup serving', grams: 170 },
      { label: '3/4 cup', grams: 125 },
    ],
    source: 'USDA FoodData Central',
    sourceVersion: 'SR Legacy 2019',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_western_white_bread',
    canonicalName: 'White Bread Slice',
    localNames: ['পাউরুটি', 'White Pauruti'],
    aliases: ['Sandwich Bread', 'White Toast Bread'],
    cuisineTags: ['western', 'staple'],
    category: 'grain',
    caloriesPer100g: 265,
    proteinPer100g: 9.0,
    carbsPer100g: 49.0,
    fatPer100g: 3.2,
    fiberPer100g: 2.7,
    commonServings: [
      { label: '1 slice', grams: 30 },
      { label: '2 slices (sandwich portion)', grams: 60 },
    ],
    source: 'USDA FoodData Central',
    sourceVersion: 'SR Legacy 2019',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_western_whole_wheat_bread',
    canonicalName: 'Whole Wheat Bread Slice',
    localNames: ['হোল হুইট পাউরুটি', 'Brown Bread'],
    aliases: ['Brown Bread', '100% Whole Wheat Bread'],
    cuisineTags: ['western', 'staple'],
    category: 'grain',
    caloriesPer100g: 247,
    proteinPer100g: 13.0,
    carbsPer100g: 41.3,
    fatPer100g: 3.4,
    fiberPer100g: 7.0,
    commonServings: [
      { label: '1 slice', grams: 35 },
      { label: '2 slices', grams: 70 },
    ],
    source: 'USDA FoodData Central',
    sourceVersion: 'SR Legacy 2019',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_western_peanut_butter',
    canonicalName: 'Peanut Butter (Smooth)',
    localNames: ['পিনাট বাটার'],
    aliases: ['Creamy Peanut Butter', 'Groundnut Butter'],
    cuisineTags: ['western', 'spread'],
    category: 'fat_oil',
    caloriesPer100g: 588,
    proteinPer100g: 25.1,
    carbsPer100g: 20.0,
    fatPer100g: 50.4,
    fiberPer100g: 6.0,
    commonServings: [
      { label: '1 tbsp', grams: 16 },
      { label: '2 tbsp (standard serving)', grams: 32 },
    ],
    source: 'USDA FoodData Central',
    sourceVersion: 'SR Legacy 2019',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_western_cheddar_cheese',
    canonicalName: 'Cheddar Cheese',
    localNames: ['চিডার চিজ'],
    aliases: ['Sharp Cheddar', 'Block Cheddar'],
    cuisineTags: ['western', 'dairy'],
    category: 'dairy',
    caloriesPer100g: 403,
    proteinPer100g: 24.9,
    carbsPer100g: 1.3,
    fatPer100g: 33.1,
    fiberPer100g: 0.0,
    commonServings: [
      { label: '1 slice', grams: 28 },
      { label: '1 cube (1 inch)', grams: 17 },
    ],
    source: 'USDA FoodData Central',
    sourceVersion: 'SR Legacy 2019',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_western_olive_oil',
    canonicalName: 'Extra Virgin Olive Oil',
    localNames: ['অলিভ অয়েল', 'Olive Tel'],
    aliases: ['Olive Oil', 'EVOO'],
    cuisineTags: ['western', 'oil'],
    category: 'fat_oil',
    caloriesPer100g: 884,
    proteinPer100g: 0.0,
    carbsPer100g: 0.0,
    fatPer100g: 100.0,
    fiberPer100g: 0.0,
    commonServings: [
      { label: '1 tsp', grams: 5 },
      { label: '1 tbsp', grams: 14 },
    ],
    source: 'USDA FoodData Central',
    sourceVersion: 'SR Legacy 2019',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_western_canned_tuna',
    canonicalName: 'Canned Tuna in Water',
    localNames: ['টুনা মাছ ক্যান'],
    aliases: ['Tuna Chunks in Springwater', 'Canned Tuna Light'],
    cuisineTags: ['western', 'seafood', 'high_protein'],
    category: 'protein',
    caloriesPer100g: 116,
    proteinPer100g: 25.5,
    carbsPer100g: 0.0,
    fatPer100g: 0.8,
    fiberPer100g: 0.0,
    commonServings: [
      { label: '1 drained can', grams: 120 },
      { label: '1/2 can', grams: 60 },
    ],
    source: 'USDA FoodData Central',
    sourceVersion: 'SR Legacy 2019',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_western_whey_protein',
    canonicalName: 'Whey Protein Isolate Powder',
    localNames: ['হুই প্রোটিন'],
    aliases: ['Whey Isolate', 'Protein Powder Vanilla/Unflavored'],
    cuisineTags: ['western', 'supplement', 'high_protein'],
    category: 'protein',
    caloriesPer100g: 375,
    proteinPer100g: 85.0,
    carbsPer100g: 3.0,
    fatPer100g: 1.5,
    fiberPer100g: 0.0,
    commonServings: [
      { label: '1 scoop', grams: 30 },
      { label: '2 scoops', grams: 60 },
    ],
    source: 'Nutrition Facts Label Average',
    sourceVersion: '2024',
    verifiedAt: '2026-01-15',
  },

  // =========================================================================
  // 3. GENERIC STAPLES & PRODUCE (8 items)
  // =========================================================================
  {
    id: 'food_generic_banana',
    canonicalName: 'Fresh Banana',
    localNames: ['কলা', 'পাকা কলা', 'Kola', 'Shobri Kola', 'Shagor Kola'],
    aliases: ['Banana Raw', 'Cavendish Banana'],
    cuisineTags: ['generic', 'fruit'],
    category: 'fruit',
    caloriesPer100g: 89,
    proteinPer100g: 1.1,
    carbsPer100g: 22.8,
    fatPer100g: 0.3,
    fiberPer100g: 2.6,
    commonServings: [
      { label: '1 medium banana', grams: 118 },
      { label: '1 small banana', grams: 80 },
    ],
    source: 'USDA FoodData Central',
    sourceVersion: 'SR Legacy 2019',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_generic_apple',
    canonicalName: 'Fresh Apple',
    localNames: ['আপেল', 'Apple'],
    aliases: ['Raw Apple with Skin', 'Fuji Apple', 'Gala Apple'],
    cuisineTags: ['generic', 'fruit'],
    category: 'fruit',
    caloriesPer100g: 52,
    proteinPer100g: 0.3,
    carbsPer100g: 13.8,
    fatPer100g: 0.2,
    fiberPer100g: 2.4,
    commonServings: [
      { label: '1 medium apple', grams: 182 },
      { label: '1 small apple', grams: 140 },
    ],
    source: 'USDA FoodData Central',
    sourceVersion: 'SR Legacy 2019',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_generic_boiled_potato',
    canonicalName: 'Boiled Potato (Skinless)',
    localNames: ['সিদ্ধ আলু', 'Sheddho Alu'],
    aliases: ['Cooked Potato', 'Plain Boiled Potato'],
    cuisineTags: ['generic', 'staple', 'vegetable'],
    category: 'vegetable',
    caloriesPer100g: 87,
    proteinPer100g: 1.9,
    carbsPer100g: 20.1,
    fatPer100g: 0.1,
    fiberPer100g: 1.8,
    commonServings: [
      { label: '1 medium potato', grams: 150 },
      { label: '1 small potato', grams: 90 },
    ],
    source: 'USDA FoodData Central',
    sourceVersion: 'SR Legacy 2019',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_generic_raw_almonds',
    canonicalName: 'Raw Whole Almonds',
    localNames: ['কাঠবাদাম', 'Kath Badam'],
    aliases: ['Almonds', 'Natural Almonds'],
    cuisineTags: ['generic', 'nuts'],
    category: 'fat_oil',
    caloriesPer100g: 579,
    proteinPer100g: 21.2,
    carbsPer100g: 21.6,
    fatPer100g: 49.9,
    fiberPer100g: 12.5,
    commonServings: [
      { label: '1 handful (approx 23 nuts)', grams: 28 },
      { label: '10 almonds', grams: 12 },
    ],
    source: 'USDA FoodData Central',
    sourceVersion: 'SR Legacy 2019',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_generic_cooked_chickpeas',
    canonicalName: 'Cooked Chickpeas / Garbanzo Beans',
    localNames: ['সিদ্ধ ছোলা', 'Sheddho Chhola'],
    aliases: ['Boiled Chana', 'Kabuli Chana Cooked'],
    cuisineTags: ['generic', 'pulse'],
    category: 'pulse',
    caloriesPer100g: 164,
    proteinPer100g: 8.9,
    carbsPer100g: 27.4,
    fatPer100g: 2.6,
    fiberPer100g: 7.6,
    commonServings: [
      { label: '1/2 cup cooked', grams: 100 },
      { label: '1 cup cooked', grams: 200 },
    ],
    source: 'USDA FoodData Central',
    sourceVersion: 'SR Legacy 2019',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_generic_raw_broccoli',
    canonicalName: 'Raw Broccoli',
    localNames: ['ব্রকলি', 'Broccoli'],
    aliases: ['Broccoli Florets', 'Fresh Broccoli'],
    cuisineTags: ['generic', 'vegetable'],
    category: 'vegetable',
    caloriesPer100g: 34,
    proteinPer100g: 2.8,
    carbsPer100g: 6.6,
    fatPer100g: 0.4,
    fiberPer100g: 2.6,
    commonServings: [
      { label: '1 cup chopped florets', grams: 91 },
      { label: '1 medium stalk', grams: 150 },
    ],
    source: 'USDA FoodData Central',
    sourceVersion: 'SR Legacy 2019',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_generic_cucumber',
    canonicalName: 'Fresh Cucumber (with peel)',
    localNames: ['শসা', 'Shosha'],
    aliases: ['Salad Cucumber', 'Sliced Cucumber'],
    cuisineTags: ['generic', 'vegetable', 'salad'],
    category: 'vegetable',
    caloriesPer100g: 15,
    proteinPer100g: 0.7,
    carbsPer100g: 3.6,
    fatPer100g: 0.1,
    fiberPer100g: 0.5,
    commonServings: [
      { label: '1 whole medium cucumber', grams: 200 },
      { label: '1/2 cucumber (sliced salad portion)', grams: 100 },
    ],
    source: 'USDA FoodData Central',
    sourceVersion: 'SR Legacy 2019',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_generic_white_sugar',
    canonicalName: 'Granulated White Sugar',
    localNames: ['চিনি', 'Chini'],
    aliases: ['Table Sugar', 'Sucrose'],
    cuisineTags: ['generic', 'sweetener'],
    category: 'grain',
    caloriesPer100g: 387,
    proteinPer100g: 0.0,
    carbsPer100g: 100.0,
    fatPer100g: 0.0,
    fiberPer100g: 0.0,
    commonServings: [
      { label: '1 tsp (tea spoonful)', grams: 4 },
      { label: '1 tbsp', grams: 12 },
    ],
    source: 'USDA FoodData Central',
    sourceVersion: 'SR Legacy 2019',
    verifiedAt: '2026-01-15',
  },

  // =========================================================================
  // 4. BRANDED & PACKAGED GOODS (7 items)
  // =========================================================================
  {
    id: 'food_brand_pran_uht_milk',
    canonicalName: 'Pran UHT Full Cream Milk',
    localNames: ['প্রাণ ইউএইচটি দুধ', 'Pran Milk Pack'],
    aliases: ['Pran Tetra Pak Milk', 'Pran UHT Milk 200ml'],
    cuisineTags: ['packaged', 'bengali', 'dairy'],
    category: 'packaged',
    caloriesPer100g: 65,
    proteinPer100g: 3.3,
    carbsPer100g: 4.8,
    fatPer100g: 3.6,
    fiberPer100g: 0.0,
    commonServings: [
      { label: '1 tetra pack (200ml)', grams: 206 },
      { label: '1 glass (250ml)', grams: 258 },
    ],
    source: 'Pran Dairy Nutrition Label',
    sourceVersion: '2024-v1',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_brand_aarong_tok_doi',
    canonicalName: 'Aarong Dairy Plain Sour Curd / Tok Doi',
    localNames: ['আড়ং টক দই', 'Aarong Tok Doi', 'Tok Doi'],
    aliases: ['Aarong Plain Curd', 'Aarong Sour Yogurt'],
    cuisineTags: ['packaged', 'bengali', 'dairy'],
    category: 'packaged',
    caloriesPer100g: 62,
    proteinPer100g: 3.5,
    carbsPer100g: 4.6,
    fatPer100g: 3.2,
    fiberPer100g: 0.0,
    commonServings: [
      { label: '1 small cup (100g)', grams: 100 },
      { label: '1 bowl portion (200g)', grams: 200 },
      { label: '1 full tub (500g)', grams: 500 },
    ],
    source: 'BRAC Aarong Dairy Product Specs',
    sourceVersion: '2024',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_brand_nestle_everyday_powder',
    canonicalName: 'Nestle Everyday Dairy Whitener / Milk Powder',
    localNames: ['নেসলে এভরিডে দুধ', 'Everyday Gura Dudh'],
    aliases: ['Everyday Milk Powder', 'Nestle Everyday Powder'],
    cuisineTags: ['packaged', 'dairy'],
    category: 'packaged',
    caloriesPer100g: 440,
    proteinPer100g: 15.0,
    carbsPer100g: 52.0,
    fatPer100g: 19.0,
    fiberPer100g: 0.0,
    commonServings: [
      { label: '1 tbsp for tea/coffee', grams: 10 },
      { label: '1 sachet (single cup)', grams: 12 },
    ],
    source: 'Nestle Bangladesh Packaging Facts',
    sourceVersion: '2024',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_brand_maggi_masala_noodles',
    canonicalName: 'Maggi 2-Minute Masala Noodles',
    localNames: ['ম্যাগি ২-মিনিট নুডলস', 'Maggi Noodles'],
    aliases: ['Maggi Masala Instant Noodles', 'Maggi Single Pack'],
    cuisineTags: ['packaged', 'instant_food'],
    category: 'packaged',
    caloriesPer100g: 427,
    proteinPer100g: 8.0,
    carbsPer100g: 63.5,
    fatPer100g: 15.7,
    fiberPer100g: 3.6,
    commonServings: [
      { label: '1 single packet (dry with tastemaker)', grams: 70 },
    ],
    source: 'Nestle Bangladesh Packaging Facts',
    sourceVersion: '2024',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_brand_olympic_energy_plus',
    canonicalName: 'Olympic Energy Plus Biscuit',
    localNames: ['অলিম্পিক এনার্জি প্লাস বিস্কুট', 'Energy Plus Biscuit'],
    aliases: ['Energy Plus Glucose Biscuit', 'Olympic Biscuit'],
    cuisineTags: ['packaged', 'snack'],
    category: 'packaged',
    caloriesPer100g: 465,
    proteinPer100g: 7.2,
    carbsPer100g: 74.0,
    fatPer100g: 15.5,
    fiberPer100g: 1.8,
    commonServings: [
      { label: '2 biscuits (snack portion)', grams: 24 },
      { label: '4 biscuits', grams: 48 },
      { label: '1 small pack (60g)', grams: 60 },
    ],
    source: 'Olympic Industries Ltd Label',
    sourceVersion: '2023',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_brand_nutella_spread',
    canonicalName: 'Nutella Hazelnut Cocoa Spread',
    localNames: ['নুটেলা স্প্রেড', 'Nutella'],
    aliases: ['Nutella Hazelnut Spread', 'Ferrero Nutella'],
    cuisineTags: ['packaged', 'western', 'spread'],
    category: 'packaged',
    caloriesPer100g: 539,
    proteinPer100g: 6.3,
    carbsPer100g: 57.5,
    fatPer100g: 30.9,
    fiberPer100g: 3.0,
    commonServings: [
      { label: '1 tbsp (15g)', grams: 15 },
      { label: '2 tbsp portion (30g)', grams: 30 },
    ],
    source: 'Ferrero Nutrition Facts Label',
    sourceVersion: '2024',
    verifiedAt: '2026-01-15',
  },
  {
    id: 'food_brand_coca_cola_can',
    canonicalName: 'Coca-Cola Regular Can (Soft Drink)',
    localNames: ['কোকাকোলা', 'Coca Cola 250ml'],
    aliases: ['Coke Original', 'Coca-Cola 250ml Can'],
    cuisineTags: ['packaged', 'beverage'],
    category: 'packaged',
    caloriesPer100g: 42,
    proteinPer100g: 0.0,
    carbsPer100g: 10.6,
    fatPer100g: 0.0,
    fiberPer100g: 0.0,
    commonServings: [
      { label: '1 mini can (250ml)', grams: 250 },
      { label: '1 standard can (330ml)', grams: 330 },
    ],
    source: 'The Coca-Cola Company Bangladesh Facts',
    sourceVersion: '2024',
    verifiedAt: '2026-01-15',
  },
];
